[0m15:43:03.187404 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6ce687f9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6ce46173d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6ce4616250>]}


============================== 15:43:03.207060 | f0b2c889-f0bd-4ab1-b06f-b53a65379707 ==============================
[0m15:43:03.207060 [info ] [MainThread]: Running with dbt=1.9.3
[0m15:43:03.211130 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/root/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt build', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:43:03.215857 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /usr/app/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:43:03.222594 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.21082681, "process_in_blocks": "0", "process_kernel_time": 0.329457, "process_mem_max_rss": "89136", "process_out_blocks": "56", "process_user_time": 3.074937}
[0m15:43:03.228622 [debug] [MainThread]: Command `dbt build` failed at 15:43:03.228222 after 0.22 seconds
[0m15:43:03.232519 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6ce467a0d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6ce4620cd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f6ce4694f90>]}
[0m15:43:03.235430 [debug] [MainThread]: Flushing usage events
[0m15:43:03.727622 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:48:40.119844 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4c14d63b90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4c16f8ffd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4c15255350>]}


============================== 15:48:40.126710 | 97956a3b-3b29-485a-9bc4-1ecbbd8d259d ==============================
[0m15:48:40.126710 [info ] [MainThread]: Running with dbt=1.9.3
[0m15:48:40.129810 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt build', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:48:40.133805 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /usr/app/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:48:40.140034 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.08782516, "process_in_blocks": "0", "process_kernel_time": 0.101249, "process_mem_max_rss": "88532", "process_out_blocks": "0", "process_user_time": 1.093493}
[0m15:48:40.143838 [debug] [MainThread]: Command `dbt build` failed at 15:48:40.143651 after 0.09 seconds
[0m15:48:40.147684 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4c14da9150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4c14d40c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4c14d94f10>]}
[0m15:48:40.148976 [debug] [MainThread]: Flushing usage events
[0m15:48:40.543797 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:49:57.719812 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8d694cd510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8d694b3390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8d69bbb350>]}


============================== 15:49:57.726955 | 5ddabc5b-af7b-4d38-995c-2f379213e4d4 ==============================
[0m15:49:57.726955 [info ] [MainThread]: Running with dbt=1.9.3
[0m15:49:57.730273 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': '/usr/app/logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt build', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:49:57.742139 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.postgres'
[0m15:49:57.743412 [error] [MainThread]: Encountered an error:
Runtime Error
  Credentials in profile "data_pipeline", target "dev" invalid: Runtime Error
    Could not find adapter type postgres!
[0m15:49:57.745787 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.10207198, "process_in_blocks": "0", "process_kernel_time": 0.099116, "process_mem_max_rss": "88088", "process_out_blocks": "0", "process_user_time": 1.12002}
[0m15:49:57.755149 [debug] [MainThread]: Command `dbt build` failed at 15:49:57.754706 after 0.11 seconds
[0m15:49:57.757908 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8d694daa50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8d6cdd4d10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8d6cdd42d0>]}
[0m15:49:57.758850 [debug] [MainThread]: Flushing usage events
[0m15:49:58.131106 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:52:15.898631 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcec7599c50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcec7401010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcec7401fd0>]}


============================== 15:52:15.904238 | 0bb2e2e1-338e-4e07-bf89-4a7aa954cdf8 ==============================
[0m15:52:15.904238 [info ] [MainThread]: Running with dbt=1.9.3
[0m15:52:15.906953 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': '/usr/app/logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt build', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:52:15.980427 [warn ] [MainThread]: [[33mWARNING[0m]: Deprecated functionality
The `source-paths` config has been renamed to `model-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
[0m15:52:15.982443 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'deprecation', 'label': '0bb2e2e1-338e-4e07-bf89-4a7aa954cdf8', 'property_': 'warn', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcec5ccfdd0>]}
[0m15:52:16.079658 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '0bb2e2e1-338e-4e07-bf89-4a7aa954cdf8', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcec74c1550>]}
[0m15:52:16.132207 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '0bb2e2e1-338e-4e07-bf89-4a7aa954cdf8', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcec9808110>]}
[0m15:52:16.135224 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m15:52:16.215814 [debug] [MainThread]: checksum: 5671c00892cdbcef29c3b00cc5ba7510c3d18a35c883caeb9ab9ee266dc29c8f, vars: {}, profile: , target: , version: 1.9.3
[0m15:52:16.222138 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m15:52:16.223122 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '0bb2e2e1-338e-4e07-bf89-4a7aa954cdf8', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcec5afa590>]}
[0m15:52:16.915012 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '0bb2e2e1-338e-4e07-bf89-4a7aa954cdf8', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcec5b23910>]}
[0m15:52:16.970003 [debug] [MainThread]: Wrote artifact WritableManifest to /usr/app/target/manifest.json
[0m15:52:16.976821 [debug] [MainThread]: Wrote artifact SemanticManifest to /usr/app/target/semantic_manifest.json
[0m15:52:17.017532 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '0bb2e2e1-338e-4e07-bf89-4a7aa954cdf8', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcec583b610>]}
[0m15:52:17.018669 [info ] [MainThread]: Found 433 macros
[0m15:52:17.023529 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m15:52:17.027508 [debug] [MainThread]: Command end result
[0m15:52:17.067548 [debug] [MainThread]: Wrote artifact WritableManifest to /usr/app/target/manifest.json
[0m15:52:17.072175 [debug] [MainThread]: Wrote artifact SemanticManifest to /usr/app/target/semantic_manifest.json
[0m15:52:17.078068 [debug] [MainThread]: Wrote artifact RunExecutionResult to /usr/app/target/run_results.json
[0m15:52:17.080278 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": true, "command_wall_clock_time": 1.2436041, "process_in_blocks": "0", "process_kernel_time": 0.165775, "process_mem_max_rss": "102264", "process_out_blocks": "120", "process_user_time": 2.258693}
[0m15:52:17.081187 [debug] [MainThread]: Command `dbt build` succeeded at 15:52:17.081074 after 1.24 seconds
[0m15:52:17.082094 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcec740bad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcecaef0c50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fcecaef0c90>]}
[0m15:52:17.082958 [debug] [MainThread]: Flushing usage events
[0m15:52:17.530092 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:53:29.519937 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff7c387af90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff7c3b73210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff7c376b590>]}


============================== 15:53:29.526649 | 2594c392-d711-4664-b4f3-c68fde9f2368 ==============================
[0m15:53:29.526649 [info ] [MainThread]: Running with dbt=1.9.3
[0m15:53:29.528409 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/root/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': '/usr/app/logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt build', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:53:29.672574 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '2594c392-d711-4664-b4f3-c68fde9f2368', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff7c35fd310>]}
[0m15:53:29.719370 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '2594c392-d711-4664-b4f3-c68fde9f2368', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff7c59f83d0>]}
[0m15:53:29.721229 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m15:53:29.772668 [debug] [MainThread]: checksum: 5671c00892cdbcef29c3b00cc5ba7510c3d18a35c883caeb9ab9ee266dc29c8f, vars: {}, profile: , target: , version: 1.9.3
[0m15:53:29.823454 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m15:53:29.825119 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '2594c392-d711-4664-b4f3-c68fde9f2368', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff7c457c890>]}
[0m15:53:30.495381 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '2594c392-d711-4664-b4f3-c68fde9f2368', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff7c1d1b450>]}
[0m15:53:30.558194 [debug] [MainThread]: Wrote artifact WritableManifest to /usr/app/target/manifest.json
[0m15:53:30.566348 [debug] [MainThread]: Wrote artifact SemanticManifest to /usr/app/target/semantic_manifest.json
[0m15:53:30.594869 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '2594c392-d711-4664-b4f3-c68fde9f2368', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff7c1a85d10>]}
[0m15:53:30.596645 [info ] [MainThread]: Found 433 macros
[0m15:53:30.602276 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m15:53:30.606316 [debug] [MainThread]: Command end result
[0m15:53:30.645856 [debug] [MainThread]: Wrote artifact WritableManifest to /usr/app/target/manifest.json
[0m15:53:30.652081 [debug] [MainThread]: Wrote artifact SemanticManifest to /usr/app/target/semantic_manifest.json
[0m15:53:30.658680 [debug] [MainThread]: Wrote artifact RunExecutionResult to /usr/app/target/run_results.json
[0m15:53:30.660191 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": true, "command_wall_clock_time": 1.2152436, "process_in_blocks": "0", "process_kernel_time": 0.111144, "process_mem_max_rss": "102336", "process_out_blocks": "0", "process_user_time": 2.101643}
[0m15:53:30.661034 [debug] [MainThread]: Command `dbt build` succeeded at 15:53:30.660928 after 1.22 seconds
[0m15:53:30.661773 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff7c37db690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff7c379fa90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff7c70ec290>]}
[0m15:53:30.663539 [debug] [MainThread]: Flushing usage events
[0m15:53:31.079143 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m06:34:09.862941 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7efcc6294910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7efcc67ad6d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7efcc6296190>]}


============================== 06:34:09.882528 | 62a9f0e3-b9bc-4eb9-9d85-15c6cf3fc9da ==============================
[0m06:34:09.882528 [info ] [MainThread]: Running with dbt=1.9.3
[0m06:34:09.888617 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': '/usr/app/logs', 'debug': 'False', 'profiles_dir': '/root/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt build', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m06:34:10.164593 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '62a9f0e3-b9bc-4eb9-9d85-15c6cf3fc9da', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7efcc6f83910>]}
[0m06:34:10.255655 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '62a9f0e3-b9bc-4eb9-9d85-15c6cf3fc9da', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7efcc85044d0>]}
[0m06:34:10.259175 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m06:34:10.378517 [debug] [MainThread]: checksum: 5671c00892cdbcef29c3b00cc5ba7510c3d18a35c883caeb9ab9ee266dc29c8f, vars: {}, profile: , target: , version: 1.9.3
[0m06:34:10.525874 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m06:34:10.528181 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m06:34:10.541071 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '62a9f0e3-b9bc-4eb9-9d85-15c6cf3fc9da', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7efcc6105910>]}
[0m06:34:10.660627 [debug] [MainThread]: Wrote artifact WritableManifest to /usr/app/target/manifest.json
[0m06:34:10.675906 [debug] [MainThread]: Wrote artifact SemanticManifest to /usr/app/target/semantic_manifest.json
[0m06:34:10.800505 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '62a9f0e3-b9bc-4eb9-9d85-15c6cf3fc9da', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7efcc43c6d90>]}
[0m06:34:10.803122 [info ] [MainThread]: Found 433 macros
[0m06:34:10.807694 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m06:34:10.812799 [debug] [MainThread]: Command end result
[0m06:34:10.872343 [debug] [MainThread]: Wrote artifact WritableManifest to /usr/app/target/manifest.json
[0m06:34:10.882526 [debug] [MainThread]: Wrote artifact SemanticManifest to /usr/app/target/semantic_manifest.json
[0m06:34:10.895624 [debug] [MainThread]: Wrote artifact RunExecutionResult to /usr/app/target/run_results.json
[0m06:34:10.899415 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": true, "command_wall_clock_time": 1.1831601, "process_in_blocks": "0", "process_kernel_time": 0.424192, "process_mem_max_rss": "102352", "process_out_blocks": "0", "process_user_time": 2.63605}
[0m06:34:10.901550 [debug] [MainThread]: Command `dbt build` succeeded at 06:34:10.901298 after 1.19 seconds
[0m06:34:10.903259 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7efcc60fe150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7efcc9d61750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7efcc47e9510>]}
[0m06:34:10.904721 [debug] [MainThread]: Flushing usage events
[0m06:34:11.608594 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:47:35.746238 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232ADA17050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232ADA17020>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232AD9C4DD0>]}


============================== 11:47:35.760719 | 75bcf745-6a8e-4256-813e-24b2afbcad44 ==============================
[0m11:47:35.760719 [info ] [MainThread]: Running with dbt=1.9.4
[0m11:47:35.762480 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'C:\\Project\\DataPipeline\\dags\\dbt_project\\logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Gaurav Chugh\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt build', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:47:36.070029 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '75bcf745-6a8e-4256-813e-24b2afbcad44', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232ADA6D9D0>]}
[0m11:47:36.148814 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '75bcf745-6a8e-4256-813e-24b2afbcad44', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232AE9EDB50>]}
[0m11:47:36.152658 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m11:47:36.498188 [debug] [MainThread]: checksum: b5597158181700c50f5bc1c71fe28b37a6fb85633dc5323885263678b6bc782c, vars: {}, profile: , target: , version: 1.9.4
[0m11:47:36.548444 [info ] [MainThread]: Unable to do partial parsing because of a version mismatch
[0m11:47:36.548444 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '75bcf745-6a8e-4256-813e-24b2afbcad44', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232AE042C90>]}
[0m11:47:37.488500 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '75bcf745-6a8e-4256-813e-24b2afbcad44', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232AD07FB00>]}
[0m11:47:37.550414 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Project\DataPipeline\dags\dbt_project\target\manifest.json
[0m11:47:37.553539 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Project\DataPipeline\dags\dbt_project\target\semantic_manifest.json
[0m11:47:37.608891 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '75bcf745-6a8e-4256-813e-24b2afbcad44', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232AFD4D6A0>]}
[0m11:47:37.608891 [info ] [MainThread]: Found 433 macros
[0m11:47:37.611240 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m11:47:37.611240 [debug] [MainThread]: Command end result
[0m11:47:37.638132 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Project\DataPipeline\dags\dbt_project\target\manifest.json
[0m11:47:37.642242 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Project\DataPipeline\dags\dbt_project\target\semantic_manifest.json
[0m11:47:37.643990 [debug] [MainThread]: Wrote artifact RunExecutionResult to C:\Project\DataPipeline\dags\dbt_project\target\run_results.json
[0m11:47:37.643990 [debug] [MainThread]: Command `dbt build` succeeded at 11:47:37.643990 after 2.26 seconds
[0m11:47:37.643990 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232AFBCCA70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232AD989D00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232AFD3C2C0>]}
[0m11:47:37.643990 [debug] [MainThread]: Flushing usage events
[0m11:47:38.339901 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:12:54.148378 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000269774C3C50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000269774C3CB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000269774C3BC0>]}


============================== 12:12:54.156819 | 40a90560-5014-4d42-94e0-b1e26b57da07 ==============================
[0m12:12:54.156819 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:12:54.156819 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Gaurav Chugh\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'C:\\Project\\DataPipeline\\dags\\dbt_project\\logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt build', 'send_anonymous_usage_stats': 'True'}
[0m12:12:54.511965 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '40a90560-5014-4d42-94e0-b1e26b57da07', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000269775311F0>]}
[0m12:12:54.599412 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '40a90560-5014-4d42-94e0-b1e26b57da07', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026977AA0440>]}
[0m12:12:54.599412 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m12:12:54.952706 [debug] [MainThread]: checksum: b5597158181700c50f5bc1c71fe28b37a6fb85633dc5323885263678b6bc782c, vars: {}, profile: , target: , version: 1.9.4
[0m12:12:55.082244 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m12:12:55.082244 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m12:12:55.091187 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '40a90560-5014-4d42-94e0-b1e26b57da07', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026978B0C410>]}
[0m12:12:55.142606 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Project\DataPipeline\dags\dbt_project\target\manifest.json
[0m12:12:55.151450 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Project\DataPipeline\dags\dbt_project\target\semantic_manifest.json
[0m12:12:55.214977 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '40a90560-5014-4d42-94e0-b1e26b57da07', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026978B35490>]}
[0m12:12:55.214977 [info ] [MainThread]: Found 433 macros
[0m12:12:55.214977 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m12:12:55.214977 [debug] [MainThread]: Command end result
[0m12:12:55.242896 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Project\DataPipeline\dags\dbt_project\target\manifest.json
[0m12:12:55.249444 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Project\DataPipeline\dags\dbt_project\target\semantic_manifest.json
[0m12:12:55.249444 [debug] [MainThread]: Wrote artifact RunExecutionResult to C:\Project\DataPipeline\dags\dbt_project\target\run_results.json
[0m12:12:55.256266 [debug] [MainThread]: Command `dbt build` succeeded at 12:12:55.256266 after 1.48 seconds
[0m12:12:55.258431 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026977A0CFB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026978B01E80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026978B03500>]}
[0m12:12:55.258431 [debug] [MainThread]: Flushing usage events
[0m12:12:55.624546 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:40:48.162916 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228C9086F30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228C9086E40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228C9B2FC20>]}


============================== 12:40:48.172520 | b4abb57e-dc75-432a-9de5-c66d682406aa ==============================
[0m12:40:48.172520 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:40:48.173580 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'C:\\Project\\DataPipeline\\dags\\dbt_project\\logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Gaurav Chugh\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt build', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:40:48.612421 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'b4abb57e-dc75-432a-9de5-c66d682406aa', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228C9C9DC70>]}
[0m12:40:48.716510 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'b4abb57e-dc75-432a-9de5-c66d682406aa', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228C8A68620>]}
[0m12:40:48.725882 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m12:40:49.165970 [debug] [MainThread]: checksum: b5597158181700c50f5bc1c71fe28b37a6fb85633dc5323885263678b6bc782c, vars: {}, profile: , target: , version: 1.9.4
[0m12:40:49.275232 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m12:40:49.276286 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m12:40:49.283426 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'b4abb57e-dc75-432a-9de5-c66d682406aa', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228CA1C5550>]}
[0m12:40:49.320584 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Project\DataPipeline\dags\dbt_project\target\manifest.json
[0m12:40:49.333395 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Project\DataPipeline\dags\dbt_project\target\semantic_manifest.json
[0m12:40:49.608564 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'b4abb57e-dc75-432a-9de5-c66d682406aa', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228CB771EB0>]}
[0m12:40:49.609187 [info ] [MainThread]: Found 433 macros
[0m12:40:49.611746 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m12:40:49.614187 [debug] [MainThread]: Command end result
[0m12:40:49.635251 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Project\DataPipeline\dags\dbt_project\target\manifest.json
[0m12:40:49.638539 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Project\DataPipeline\dags\dbt_project\target\semantic_manifest.json
[0m12:40:49.644851 [debug] [MainThread]: Wrote artifact RunExecutionResult to C:\Project\DataPipeline\dags\dbt_project\target\run_results.json
[0m12:40:49.646638 [debug] [MainThread]: Command `dbt build` succeeded at 12:40:49.646254 after 1.85 seconds
[0m12:40:49.646982 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228C93DEEA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228C9368560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228CB37F950>]}
[0m12:40:49.646982 [debug] [MainThread]: Flushing usage events
[0m12:40:50.012377 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m04:40:32.256868 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025FCE3A6E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025FCE2B3B00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025FCB71FAD0>]}


============================== 04:40:32.261622 | defed430-f847-482a-8614-e44e89ea1320 ==============================
[0m04:40:32.261622 [info ] [MainThread]: Running with dbt=1.9.6
[0m04:40:32.261622 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Gaurav Chugh\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'C:\\Project\\DataPipeline\\dags\\dbt_project\\logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt build --project-dir C:\\Project\\DataPipeline\\dags\\dbt_project', 'send_anonymous_usage_stats': 'True'}
[0m04:40:32.461867 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'defed430-f847-482a-8614-e44e89ea1320', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025FCB954410>]}
[0m04:40:32.525350 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'defed430-f847-482a-8614-e44e89ea1320', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025FCE820C50>]}
[0m04:40:32.525350 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m04:40:32.694696 [debug] [MainThread]: checksum: dd6dc1e5178459e3de3bf2eeb7c86bed4be2266c311fce8c15d86eb4ff94e7ad, vars: {}, profile: , target: , version: 1.9.6
[0m04:40:32.725307 [info ] [MainThread]: Unable to do partial parsing because of a version mismatch
[0m04:40:32.725307 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'defed430-f847-482a-8614-e44e89ea1320', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025FCE3A6720>]}
[0m04:40:33.323070 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'defed430-f847-482a-8614-e44e89ea1320', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025FD00675F0>]}
[0m04:40:33.353329 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Project\DataPipeline\dags\dbt_project\target\manifest.json
[0m04:40:33.353329 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Project\DataPipeline\dags\dbt_project\target\semantic_manifest.json
[0m04:40:33.447998 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'defed430-f847-482a-8614-e44e89ea1320', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025FD0066D20>]}
[0m04:40:33.447998 [info ] [MainThread]: Found 433 macros
[0m04:40:33.447998 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m04:40:33.447998 [debug] [MainThread]: Command end result
[0m04:40:33.463740 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Project\DataPipeline\dags\dbt_project\target\manifest.json
[0m04:40:33.463740 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Project\DataPipeline\dags\dbt_project\target\semantic_manifest.json
[0m04:40:33.463740 [debug] [MainThread]: Wrote artifact RunExecutionResult to C:\Project\DataPipeline\dags\dbt_project\target\run_results.json
[0m04:40:33.463740 [debug] [MainThread]: Command `dbt build` succeeded at 04:40:33.463740 after 1.41 seconds
[0m04:40:33.463740 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025FCE318140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025FCDCB2120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025FCDCB1400>]}
[0m04:40:33.463740 [debug] [MainThread]: Flushing usage events
[0m04:40:33.887203 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m04:45:22.326974 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002982DD963F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000298314EACF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000298314E92E0>]}


============================== 04:45:22.331343 | 8da6c4b5-9029-4879-a4a3-8266baa7e971 ==============================
[0m04:45:22.331343 [info ] [MainThread]: Running with dbt=1.9.6
[0m04:45:22.331343 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'C:\\Project\\DataPipeline\\dags\\dbt_project\\logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Gaurav Chugh\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt build --project-dir C:\\Project\\DataPipeline\\dags\\dbt_project', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m04:45:22.512532 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '8da6c4b5-9029-4879-a4a3-8266baa7e971', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029831812330>]}
[0m04:45:22.586901 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '8da6c4b5-9029-4879-a4a3-8266baa7e971', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029832C16A80>]}
[0m04:45:22.586901 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m04:45:22.799113 [debug] [MainThread]: checksum: dd6dc1e5178459e3de3bf2eeb7c86bed4be2266c311fce8c15d86eb4ff94e7ad, vars: {}, profile: , target: , version: 1.9.6
[0m04:45:22.824405 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m04:45:22.824405 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '8da6c4b5-9029-4879-a4a3-8266baa7e971', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002983330F2F0>]}
[0m04:45:23.307970 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '8da6c4b5-9029-4879-a4a3-8266baa7e971', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002983339AD20>]}
[0m04:45:23.330846 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Project\DataPipeline\dags\dbt_project\target\manifest.json
[0m04:45:23.332852 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Project\DataPipeline\dags\dbt_project\target\semantic_manifest.json
[0m04:45:23.360318 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '8da6c4b5-9029-4879-a4a3-8266baa7e971', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000298333A6930>]}
[0m04:45:23.360318 [info ] [MainThread]: Found 433 macros
[0m04:45:23.362335 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m04:45:23.362335 [debug] [MainThread]: Command end result
[0m04:45:23.372982 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Project\DataPipeline\dags\dbt_project\target\manifest.json
[0m04:45:23.376313 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Project\DataPipeline\dags\dbt_project\target\semantic_manifest.json
[0m04:45:23.380493 [debug] [MainThread]: Wrote artifact RunExecutionResult to C:\Project\DataPipeline\dags\dbt_project\target\run_results.json
[0m04:45:23.380493 [debug] [MainThread]: Command `dbt build` succeeded at 04:45:23.380493 after 1.24 seconds
[0m04:45:23.381626 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002982DD963F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002982B719A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000298318E7620>]}
[0m04:45:23.383923 [debug] [MainThread]: Flushing usage events
[0m04:45:23.797373 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m04:48:45.494263 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8E9356D20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8E8C62270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8E93569F0>]}


============================== 04:48:45.497919 | 77daa29f-0b47-4261-8a70-65b091830c85 ==============================
[0m04:48:45.497919 [info ] [MainThread]: Running with dbt=1.9.6
[0m04:48:45.498451 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Gaurav Chugh\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'C:\\Project\\DataPipeline\\dags\\dbt_project\\logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt build --project-dir C:\\Project\\DataPipeline\\dags\\dbt_project', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m04:48:45.626297 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '77daa29f-0b47-4261-8a70-65b091830c85', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8EA8E3CE0>]}
[0m04:48:45.700531 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '77daa29f-0b47-4261-8a70-65b091830c85', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8E9639D00>]}
[0m04:48:45.700531 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m04:48:45.900727 [debug] [MainThread]: checksum: dd6dc1e5178459e3de3bf2eeb7c86bed4be2266c311fce8c15d86eb4ff94e7ad, vars: {}, profile: , target: , version: 1.9.6
[0m04:48:45.934062 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m04:48:45.936960 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '77daa29f-0b47-4261-8a70-65b091830c85', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8E93565D0>]}
[0m04:48:46.819901 [error] [MainThread]: Encountered an error:
Compilation Error
  Model 'model.data_pipeline.raw_to_normalized' (../../models\raw_to_normalized.sql) depends on a source named 'raw.raw_data' which was not found
[0m04:48:46.819901 [debug] [MainThread]: Command `dbt build` failed at 04:48:46.819901 after 1.50 seconds
[0m04:48:46.819901 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8E97AB5C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8EB1D02C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8EB256240>]}
[0m04:48:46.819901 [debug] [MainThread]: Flushing usage events
[0m04:48:47.238159 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m05:00:01.823459 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002090F0BDC10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020911EB73B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020911EB4B00>]}


============================== 05:00:01.826353 | 6f92e768-44e0-4c69-9869-94e4953ff19c ==============================
[0m05:00:01.826353 [info ] [MainThread]: Running with dbt=1.9.6
[0m05:00:01.826353 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Gaurav Chugh\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'C:\\Project\\DataPipeline\\dags\\dbt_project\\logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt build --project-dir C:\\Project\\DataPipeline\\dags\\dbt_project', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m05:00:01.969232 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '6f92e768-44e0-4c69-9869-94e4953ff19c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209136A9580>]}
[0m05:00:02.018064 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '6f92e768-44e0-4c69-9869-94e4953ff19c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020912217770>]}
[0m05:00:02.018064 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m05:00:02.208140 [debug] [MainThread]: checksum: dd6dc1e5178459e3de3bf2eeb7c86bed4be2266c311fce8c15d86eb4ff94e7ad, vars: {}, profile: , target: , version: 1.9.6
[0m05:00:02.238574 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m05:00:02.239764 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '6f92e768-44e0-4c69-9869-94e4953ff19c', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002091396EF60>]}
[0m05:00:03.233558 [error] [MainThread]: Encountered an error:
Compilation Error
  Model 'model.data_pipeline.raw_to_normalized' (../../models\raw_to_normalized.sql) depends on a source named 'raw.raw_data' which was not found
[0m05:00:03.233558 [debug] [MainThread]: Command `dbt build` failed at 05:00:03.233558 after 1.60 seconds
[0m05:00:03.233558 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020911F8DBE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020911301550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209139E8E30>]}
[0m05:00:03.233558 [debug] [MainThread]: Flushing usage events
[0m05:00:03.656274 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m05:02:04.613108 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023F78174C20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023F7BCA6BD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023F7BCA4CE0>]}


============================== 05:02:04.617183 | a2fc53bb-7365-49f2-b3a0-4f80bc671ae2 ==============================
[0m05:02:04.617183 [info ] [MainThread]: Running with dbt=1.9.6
[0m05:02:04.617183 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Gaurav Chugh\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'C:\\Project\\DataPipeline\\dags\\dbt_project\\logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt build', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m05:02:04.762270 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'a2fc53bb-7365-49f2-b3a0-4f80bc671ae2', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023F79254320>]}
[0m05:02:04.804081 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'a2fc53bb-7365-49f2-b3a0-4f80bc671ae2', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023F7947FAD0>]}
[0m05:02:04.804081 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m05:02:04.966689 [debug] [MainThread]: checksum: dd6dc1e5178459e3de3bf2eeb7c86bed4be2266c311fce8c15d86eb4ff94e7ad, vars: {}, profile: , target: , version: 1.9.6
[0m05:02:04.992974 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m05:02:04.992974 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'a2fc53bb-7365-49f2-b3a0-4f80bc671ae2', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023F7D927F20>]}
[0m05:02:06.047869 [error] [MainThread]: Encountered an error:
Compilation Error
  Model 'model.data_pipeline.raw_to_normalized' (../../models\raw_to_normalized.sql) depends on a source named 'raw.raw_data' which was not found
[0m05:02:06.047869 [debug] [MainThread]: Command `dbt build` failed at 05:02:06.047869 after 1.77 seconds
[0m05:02:06.047869 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023F7901FC20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023F7B63DCD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023F7DAC8980>]}
[0m05:02:06.047869 [debug] [MainThread]: Flushing usage events
[0m05:02:06.474083 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m05:03:27.699819 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002026FF366C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002026D9C74D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000202707EC440>]}


============================== 05:03:27.701827 | a3d9a0d6-1da8-4857-abb2-44b92716f22f ==============================
[0m05:03:27.701827 [info ] [MainThread]: Running with dbt=1.9.6
[0m05:03:27.701827 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Gaurav Chugh\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'C:\\Project\\DataPipeline\\dags\\dbt_project\\logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt list --resource-type source', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m05:03:27.836619 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'a3d9a0d6-1da8-4857-abb2-44b92716f22f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000202709C34A0>]}
[0m05:03:27.886431 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'a3d9a0d6-1da8-4857-abb2-44b92716f22f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020271B54860>]}
[0m05:03:27.888438 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m05:03:28.112181 [debug] [MainThread]: checksum: dd6dc1e5178459e3de3bf2eeb7c86bed4be2266c311fce8c15d86eb4ff94e7ad, vars: {}, profile: , target: , version: 1.9.6
[0m05:03:28.148208 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m05:03:28.150217 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'a3d9a0d6-1da8-4857-abb2-44b92716f22f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000202721FB7D0>]}
[0m05:03:29.206145 [error] [MainThread]: Encountered an error:
Compilation Error
  Model 'model.data_pipeline.raw_to_normalized' (../../models\raw_to_normalized.sql) depends on a source named 'raw.raw_data' which was not found
[0m05:03:29.217687 [debug] [MainThread]: Command `dbt list` failed at 05:03:29.217687 after 1.73 seconds
[0m05:03:29.219702 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000202706E9820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000202723768A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002026F9A6120>]}
[0m05:03:29.219702 [debug] [MainThread]: Flushing usage events
[0m05:03:29.630835 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m05:04:33.377385 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002405FBC7080>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024062722600>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000240627215B0>]}


============================== 05:04:33.381251 | 5220d0e3-241a-47a7-a30c-9fab1382aa5b ==============================
[0m05:04:33.381251 [info ] [MainThread]: Running with dbt=1.9.6
[0m05:04:33.383255 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Gaurav Chugh\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'C:\\Project\\DataPipeline\\dags\\dbt_project\\logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt build', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m05:04:33.537828 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '5220d0e3-241a-47a7-a30c-9fab1382aa5b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002405FBC7080>]}
[0m05:04:33.608848 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '5220d0e3-241a-47a7-a30c-9fab1382aa5b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000240628A1C70>]}
[0m05:04:33.609850 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m05:04:33.872634 [debug] [MainThread]: checksum: dd6dc1e5178459e3de3bf2eeb7c86bed4be2266c311fce8c15d86eb4ff94e7ad, vars: {}, profile: , target: , version: 1.9.6
[0m05:04:33.910043 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m05:04:33.911062 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '5220d0e3-241a-47a7-a30c-9fab1382aa5b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000240627466C0>]}
[0m05:04:34.947580 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '5220d0e3-241a-47a7-a30c-9fab1382aa5b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000240643E5760>]}
[0m05:04:35.004983 [debug] [MainThread]: Wrote artifact WritableManifest to C:\Project\DataPipeline\dags\dbt_project\target\manifest.json
[0m05:04:35.004983 [debug] [MainThread]: Wrote artifact SemanticManifest to C:\Project\DataPipeline\dags\dbt_project\target\semantic_manifest.json
[0m05:04:35.055385 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '5220d0e3-241a-47a7-a30c-9fab1382aa5b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024063DE7740>]}
[0m05:04:35.055924 [info ] [MainThread]: Found 1 model, 21 data tests, 3 sources, 433 macros
[0m05:04:35.061956 [info ] [MainThread]: 
[0m05:04:35.062461 [info ] [MainThread]: Concurrency: 1 threads (target='dev')
[0m05:04:35.065806 [info ] [MainThread]: 
[0m05:04:35.065806 [debug] [MainThread]: Acquiring new postgres connection 'master'
[0m05:04:35.071818 [debug] [ThreadPool]: Acquiring new postgres connection 'list_datamart'
[0m05:04:35.163037 [debug] [ThreadPool]: Using postgres connection "list_datamart"
[0m05:04:35.163621 [debug] [ThreadPool]: On list_datamart: /* {"app": "dbt", "dbt_version": "1.9.6", "profile_name": "data_pipeline", "target_name": "dev", "connection_name": "list_datamart"} */

    select distinct nspname from pg_namespace
  
[0m05:04:35.163621 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m05:04:37.871039 [debug] [ThreadPool]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
could not translate host name "postgres_dw" to address: No such host is known. 

[0m05:04:40.550111 [debug] [ThreadPool]: Postgres adapter: Error running SQL: /* {"app": "dbt", "dbt_version": "1.9.6", "profile_name": "data_pipeline", "target_name": "dev", "connection_name": "list_datamart"} */

    select distinct nspname from pg_namespace
  
[0m05:04:40.552116 [debug] [ThreadPool]: Postgres adapter: Rolling back transaction.
[0m05:04:40.552116 [debug] [ThreadPool]: Postgres adapter: Error running SQL: macro list_schemas
[0m05:04:40.554122 [debug] [ThreadPool]: Postgres adapter: Rolling back transaction.
[0m05:04:40.554122 [debug] [ThreadPool]: On list_datamart: No close available on handle
[0m05:04:40.556128 [debug] [MainThread]: Connection 'master' was properly closed.
[0m05:04:40.556128 [debug] [MainThread]: Connection 'list_datamart' was properly closed.
[0m05:04:40.556128 [info ] [MainThread]: 
[0m05:04:40.558134 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 5.49 seconds (5.49s).
[0m05:04:40.558134 [error] [MainThread]: Encountered an error:
Database Error
  could not translate host name "postgres_dw" to address: No such host is known. 
  
[0m05:04:40.562145 [debug] [MainThread]: Command `dbt build` failed at 05:04:40.562145 after 7.36 seconds
[0m05:04:40.562145 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024061BA5CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024063DE5F40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024062780BF0>]}
[0m05:04:40.562145 [debug] [MainThread]: Flushing usage events
[0m05:04:40.945480 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m05:13:15.683405 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E7F2376C00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E7F24D1280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E7F1D623F0>]}


============================== 05:13:15.684222 | 9b95d384-d9cd-4efe-8429-4566bca48e79 ==============================
[0m05:13:15.684222 [info ] [MainThread]: Running with dbt=1.9.6
[0m05:13:15.687772 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Gaurav Chugh\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'C:\\Project\\DataPipeline\\dags\\dbt_project\\logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m05:13:15.702634 [info ] [MainThread]: dbt version: 1.9.6
[0m05:13:15.702634 [info ] [MainThread]: python version: 3.12.6
[0m05:13:15.702634 [info ] [MainThread]: python path: C:\Project\DataPipeline\venv\Scripts\python.exe
[0m05:13:15.703708 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m05:13:15.742996 [info ] [MainThread]: Using profiles dir at C:\Users\Gaurav Chugh\.dbt
[0m05:13:15.746837 [info ] [MainThread]: Using profiles.yml file at C:\Users\Gaurav Chugh\.dbt\profiles.yml
[0m05:13:15.746837 [info ] [MainThread]: Using dbt_project.yml file at C:\Project\DataPipeline\dags\dbt_project\dbt_project.yml
[0m05:13:15.747853 [info ] [MainThread]: adapter type: postgres
[0m05:13:15.748849 [info ] [MainThread]: adapter version: 1.9.0
[0m05:13:15.830953 [info ] [MainThread]: Configuration:
[0m05:13:15.835971 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m05:13:15.835971 [info ] [MainThread]:   dbt_project.yml file [[32mOK found and valid[0m]
[0m05:13:15.835971 [info ] [MainThread]: Required dependencies:
[0m05:13:15.835971 [debug] [MainThread]: Executing "git --help"
[0m05:13:15.875048 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m05:13:15.876049 [debug] [MainThread]: STDERR: "b''"
[0m05:13:15.876049 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m05:13:15.876049 [info ] [MainThread]: Connection:
[0m05:13:15.877051 [info ] [MainThread]:   host: localhost
[0m05:13:15.877051 [info ] [MainThread]:   port: 5432
[0m05:13:15.877051 [info ] [MainThread]:   user: dwh_user
[0m05:13:15.878049 [info ] [MainThread]:   database: datamart
[0m05:13:15.878049 [info ] [MainThread]:   schema: public
[0m05:13:15.879049 [info ] [MainThread]:   connect_timeout: 10
[0m05:13:15.879049 [info ] [MainThread]:   role: None
[0m05:13:15.879049 [info ] [MainThread]:   search_path: None
[0m05:13:15.879049 [info ] [MainThread]:   keepalives_idle: 0
[0m05:13:15.880048 [info ] [MainThread]:   sslmode: None
[0m05:13:15.880048 [info ] [MainThread]:   sslcert: None
[0m05:13:15.881048 [info ] [MainThread]:   sslkey: None
[0m05:13:15.881048 [info ] [MainThread]:   sslrootcert: None
[0m05:13:15.881048 [info ] [MainThread]:   application_name: dbt
[0m05:13:15.882048 [info ] [MainThread]:   retries: 1
[0m05:13:15.882048 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m05:13:16.021640 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m05:13:16.089851 [debug] [MainThread]: Using postgres connection "debug"
[0m05:13:16.094228 [debug] [MainThread]: On debug: select 1 as id
[0m05:13:16.094228 [debug] [MainThread]: Opening a new connection, currently in state init
[0m05:13:16.193928 [debug] [MainThread]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "dwh_user"

[0m05:13:16.242148 [debug] [MainThread]: Postgres adapter: Error running SQL: select 1 as id
[0m05:13:16.242148 [debug] [MainThread]: Postgres adapter: Rolling back transaction.
[0m05:13:16.243694 [debug] [MainThread]: On debug: No close available on handle
[0m05:13:16.243694 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m05:13:16.243694 [info ] [MainThread]: [31m1 check failed:[0m
[0m05:13:16.243694 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "dwh_user"
  

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m05:13:16.243694 [debug] [MainThread]: Command `dbt debug` failed at 05:13:16.243694 after 0.73 seconds
[0m05:13:16.243694 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m05:13:16.243694 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E7F23B2630>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E7F25E0CE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E7F25E1A00>]}
[0m05:13:16.243694 [debug] [MainThread]: Flushing usage events
[0m05:13:16.644318 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m05:15:04.130765 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001653FA51A60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001653CFFCAD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016540511400>]}


============================== 05:15:04.139506 | 3c44796f-a673-46ce-b2fc-d6ceb2f41d5f ==============================
[0m05:15:04.139506 [info ] [MainThread]: Running with dbt=1.9.6
[0m05:15:04.140013 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Gaurav Chugh\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'C:\\Project\\DataPipeline\\dags\\dbt_project\\logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m05:15:04.157986 [info ] [MainThread]: dbt version: 1.9.6
[0m05:15:04.159003 [info ] [MainThread]: python version: 3.12.6
[0m05:15:04.159999 [info ] [MainThread]: python path: C:\Project\DataPipeline\venv\Scripts\python.exe
[0m05:15:04.161332 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m05:15:04.216188 [info ] [MainThread]: Using profiles dir at C:\Users\Gaurav Chugh\.dbt
[0m05:15:04.216188 [info ] [MainThread]: Using profiles.yml file at C:\Users\Gaurav Chugh\.dbt\profiles.yml
[0m05:15:04.216188 [info ] [MainThread]: Using dbt_project.yml file at C:\Project\DataPipeline\dags\dbt_project\dbt_project.yml
[0m05:15:04.216188 [info ] [MainThread]: adapter type: postgres
[0m05:15:04.216188 [info ] [MainThread]: adapter version: 1.9.0
[0m05:15:04.353101 [info ] [MainThread]: Configuration:
[0m05:15:04.356308 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m05:15:04.356308 [info ] [MainThread]:   dbt_project.yml file [[32mOK found and valid[0m]
[0m05:15:04.356967 [info ] [MainThread]: Required dependencies:
[0m05:15:04.357677 [debug] [MainThread]: Executing "git --help"
[0m05:15:04.388965 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m05:15:04.389492 [debug] [MainThread]: STDERR: "b''"
[0m05:15:04.390015 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m05:15:04.390354 [info ] [MainThread]: Connection:
[0m05:15:04.391357 [info ] [MainThread]:   host: localhost
[0m05:15:04.391357 [info ] [MainThread]:   port: 5432
[0m05:15:04.391867 [info ] [MainThread]:   user: dwh_user
[0m05:15:04.391867 [info ] [MainThread]:   database: datamart
[0m05:15:04.392872 [info ] [MainThread]:   schema: public
[0m05:15:04.393375 [info ] [MainThread]:   connect_timeout: 10
[0m05:15:04.393375 [info ] [MainThread]:   role: None
[0m05:15:04.393375 [info ] [MainThread]:   search_path: None
[0m05:15:04.393375 [info ] [MainThread]:   keepalives_idle: 0
[0m05:15:04.394379 [info ] [MainThread]:   sslmode: None
[0m05:15:04.394379 [info ] [MainThread]:   sslcert: None
[0m05:15:04.394379 [info ] [MainThread]:   sslkey: None
[0m05:15:04.394379 [info ] [MainThread]:   sslrootcert: None
[0m05:15:04.395380 [info ] [MainThread]:   application_name: dbt
[0m05:15:04.395380 [info ] [MainThread]:   retries: 1
[0m05:15:04.396381 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m05:15:04.550624 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m05:15:04.598601 [debug] [MainThread]: Using postgres connection "debug"
[0m05:15:04.598601 [debug] [MainThread]: On debug: select 1 as id
[0m05:15:04.598601 [debug] [MainThread]: Opening a new connection, currently in state init
[0m05:15:04.661520 [debug] [MainThread]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "dwh_user"

[0m05:15:04.711324 [debug] [MainThread]: Postgres adapter: Error running SQL: select 1 as id
[0m05:15:04.711324 [debug] [MainThread]: Postgres adapter: Rolling back transaction.
[0m05:15:04.713330 [debug] [MainThread]: On debug: No close available on handle
[0m05:15:04.713330 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m05:15:04.714506 [info ] [MainThread]: [31m1 check failed:[0m
[0m05:15:04.715502 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "dwh_user"
  

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m05:15:04.716303 [debug] [MainThread]: Command `dbt debug` failed at 05:15:04.716303 after 0.80 seconds
[0m05:15:04.716303 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m05:15:04.716303 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001653CFFCAD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016540762A80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016540216870>]}
[0m05:15:04.716303 [debug] [MainThread]: Flushing usage events
[0m05:15:05.078607 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m05:16:20.273321 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F8BB7FA10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F8BB7C380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F91A95F10>]}


============================== 05:16:20.274334 | 538f267f-e6e9-469e-a327-116c19b7653c ==============================
[0m05:16:20.274334 [info ] [MainThread]: Running with dbt=1.9.6
[0m05:16:20.274334 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Gaurav Chugh\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'C:\\Project\\DataPipeline\\dags\\dbt_project\\logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m05:16:20.293732 [info ] [MainThread]: dbt version: 1.9.6
[0m05:16:20.293732 [info ] [MainThread]: python version: 3.12.6
[0m05:16:20.295740 [info ] [MainThread]: python path: C:\Project\DataPipeline\venv\Scripts\python.exe
[0m05:16:20.296254 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m05:16:20.343041 [info ] [MainThread]: Using profiles dir at C:\Users\Gaurav Chugh\.dbt
[0m05:16:20.344053 [info ] [MainThread]: Using profiles.yml file at C:\Users\Gaurav Chugh\.dbt\profiles.yml
[0m05:16:20.345053 [info ] [MainThread]: Using dbt_project.yml file at C:\Project\DataPipeline\dags\dbt_project\dbt_project.yml
[0m05:16:20.346053 [info ] [MainThread]: adapter type: postgres
[0m05:16:20.347053 [info ] [MainThread]: adapter version: 1.9.0
[0m05:16:20.418699 [info ] [MainThread]: Configuration:
[0m05:16:20.418699 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m05:16:20.418699 [info ] [MainThread]:   dbt_project.yml file [[32mOK found and valid[0m]
[0m05:16:20.418699 [info ] [MainThread]: Required dependencies:
[0m05:16:20.418699 [debug] [MainThread]: Executing "git --help"
[0m05:16:20.449237 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone      Clone a repository into a new directory\n   init       Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add        Add file contents to the index\n   mv         Move or rename a file, a directory, or a symlink\n   restore    Restore working tree files\n   rm         Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect     Use binary search to find the commit that introduced a bug\n   diff       Show changes between commits, commit and working tree, etc\n   grep       Print lines matching a pattern\n   log        Show commit logs\n   show       Show various types of objects\n   status     Show the working tree status\n\ngrow, mark and tweak your common history\n   backfill   Download missing objects in a partial clone\n   branch     List, create, or delete branches\n   commit     Record changes to the repository\n   merge      Join two or more development histories together\n   rebase     Reapply commits on top of another base tip\n   reset      Reset current HEAD to the specified state\n   switch     Switch branches\n   tag        Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch      Download objects and refs from another repository\n   pull       Fetch from and integrate with another repository or a local branch\n   push       Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m05:16:20.450720 [debug] [MainThread]: STDERR: "b''"
[0m05:16:20.451726 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m05:16:20.451726 [info ] [MainThread]: Connection:
[0m05:16:20.452725 [info ] [MainThread]:   host: localhost
[0m05:16:20.453422 [info ] [MainThread]:   port: 5432
[0m05:16:20.453422 [info ] [MainThread]:   user: dwh_user
[0m05:16:20.453422 [info ] [MainThread]:   database: datamart
[0m05:16:20.453422 [info ] [MainThread]:   schema: public
[0m05:16:20.453422 [info ] [MainThread]:   connect_timeout: 10
[0m05:16:20.453422 [info ] [MainThread]:   role: None
[0m05:16:20.453422 [info ] [MainThread]:   search_path: None
[0m05:16:20.453422 [info ] [MainThread]:   keepalives_idle: 0
[0m05:16:20.453422 [info ] [MainThread]:   sslmode: None
[0m05:16:20.456812 [info ] [MainThread]:   sslcert: None
[0m05:16:20.457315 [info ] [MainThread]:   sslkey: None
[0m05:16:20.457650 [info ] [MainThread]:   sslrootcert: None
[0m05:16:20.457650 [info ] [MainThread]:   application_name: dbt
[0m05:16:20.460105 [info ] [MainThread]:   retries: 1
[0m05:16:20.460105 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m05:16:20.627554 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m05:16:20.676235 [debug] [MainThread]: Using postgres connection "debug"
[0m05:16:20.676235 [debug] [MainThread]: On debug: select 1 as id
[0m05:16:20.676235 [debug] [MainThread]: Opening a new connection, currently in state init
[0m05:16:20.857120 [debug] [MainThread]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "dwh_user"

[0m05:16:20.996980 [debug] [MainThread]: Postgres adapter: Error running SQL: select 1 as id
[0m05:16:21.006714 [debug] [MainThread]: Postgres adapter: Rolling back transaction.
[0m05:16:21.006714 [debug] [MainThread]: On debug: No close available on handle
[0m05:16:21.006714 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m05:16:21.006714 [info ] [MainThread]: [31m1 check failed:[0m
[0m05:16:21.009641 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "dwh_user"
  

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m05:16:21.009641 [debug] [MainThread]: Command `dbt debug` failed at 05:16:21.009641 after 0.96 seconds
[0m05:16:21.009641 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m05:16:21.009641 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F917FA720>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F930177A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F91011BE0>]}
[0m05:16:21.009641 [debug] [MainThread]: Flushing usage events
[0m05:16:21.416626 [debug] [MainThread]: An error was encountered while trying to flush usage events
